apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chiaretto-app-dev
  namespace: argocd
spec:
  destination:
    namespace: 'chiaretto-app-dev'
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: .
    repoURL: https://github.com/lgchiaretto/chiaretto-app.git
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
